repos:
-   repo: local
    hooks:
    - id: isort
      name: Run isort
      entry: isort
      language: system
      exclude: \.ui|\.txt|\.zip|\.npy|\.png|\.cmd|\.icns|\.whl|\.toml|\.lock|\.md|\.qrc|\.sh|.gitignore|/gitattributes
      args: ["--profile", "black", "pyminflux"]
-   repo: local
    hooks:
    - id: black
      name: Run black
      entry: black
      language: system
      args: ["pyminflux"]
      pass_filenames: true
      exclude: \.ui|\.txt|\.zip|\.npy|\.png|\.cmd|\.icns|\.whl|\.toml|\.lock|\.md|\.qrc|\.sh|.gitignore|.gitattributes

