repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      exclude: \.ui|\.txt|\.zip|\.npy|\.png|\.cmd|\.icns|\.whl|\.toml|\.lock|\.md|\.qrc|\.sh|\.yaml|.gitignore|.gitattributes
      args: ["--profile", "black"]
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    - id: black
      pass_filenames: true
      exclude: \.ui|\.txt|\.zip|\.npy|\.png|\.cmd|\.icns|\.whl|\.toml|\.lock|\.md|\.qrc|\.sh|\.yaml|.gitignore|.gitattributes
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      pass_filenames: true
      exclude: \.ui|\.txt|\.zip|\.npy|\.png|\.cmd|\.icns|\.whl|\.toml|\.lock|\.md|\.qrc|\.sh|\.yaml|.gitignore|.gitattributes
